# Generated by Django 6.0.7 on 2026-09-24 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token de Expo')),
                ('plataforma', models.CharField(blank=True, max_length=10, verbose_name='Plataforma')),
                ('activo', models.BooleanField(default=True, help_text='Se desactiva al cerrar sesión o cuando Expo informa que la app se desinstaló.', verbose_name='Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_push', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo (notificaciones push)',
                'verbose_name_plural': 'Dispositivos (notificaciones push)',
            },
        ),
    ]
