# Generated by Django 6.0.7 on 2026-08-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_mascota_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDesparasitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa (Pulgas/Garrapatas)'), ('AMBAS', 'Ambas')], default='INTERNA', max_length=10)),
                ('producto', models.CharField(help_text='Ej: Total Full, Simparica, Bravecto', max_length=100)),
                ('dosis', models.CharField(blank=True, help_text='Ej: 1 comprimido, 0.5 ml', max_length=50, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_proxima_dosis', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Desparasitación',
                'verbose_name_plural': 'Registros de Desparasitaciones',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(help_text='Ej: Quíntuple, Antirrábica, Séxtuple', max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_proxima_dosis', models.DateField(blank=True, help_text='Para alertas y recordatorios de revacunación', null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Vacuna',
                'verbose_name_plural': 'Registros de Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('peso_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura en °C', max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='LPM', null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, help_text='RPM', null=True)),
                ('motivo_consulta', models.TextField()),
                ('anamnesis', models.TextField(blank=True, help_text='Historia del problema / Síntomas reportados por el dueño', null=True)),
                ('examen_clinico', models.TextField(blank=True, help_text='Hallazgos en la exploración física', null=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(help_text='Indicaciones, medicamentos recetados y procedimiento')),
                ('observaciones_privadas', models.TextField(blank=True, help_text='Notas internas para el equipo veterinario', null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='clientes.mascota')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
