# Generated by Django 6.0.7 on 2026-08-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_mascota_options_and_more'),
        ('historia_clinica', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='turnos.veterinario'),
        ),
        migrations.AddField(
            model_name='registrodesparasitacion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones', to='clientes.mascota'),
        ),
        migrations.AddField(
            model_name='registrodesparasitacion',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.veterinario'),
        ),
        migrations.AddField(
            model_name='registrovacuna',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='clientes.mascota'),
        ),
        migrations.AddField(
            model_name='registrovacuna',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.veterinario'),
        ),
    ]
