# Generated by Django 6.0.7 on 2026-08-10 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_historiaclinica_mascota_and_more'),
        ('historia_clinica', '0002_initial'),
        ('turnos', '0002_alter_veterinario_options_turno_actualizado_and_more'),
        ('usuarios', '0002_perfilusuario_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='veterinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medicas', to='usuarios.veterinaria', verbose_name='Veterinaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodesparasitacion',
            name='veterinaria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones_aplicadas', to='usuarios.veterinaria', verbose_name='Veterinaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrovacuna',
            name='veterinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='usuarios.veterinaria', verbose_name='Veterinaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='anamnesis',
            field=models.TextField(blank=True, help_text='Historia clínica previa / Síntomas reportados', null=True, verbose_name='Anamnesis / Síntomas'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='diagnostico',
            field=models.TextField(verbose_name='Diagnóstico Presuntivo / Definitivo'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='examen_clinico',
            field=models.TextField(blank=True, help_text='Hallazgos en la exploración física', null=True, verbose_name='Examen Físico / Clinico'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, verbose_name='FC (LPM)'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, verbose_name='FR (RPM)'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='clientes.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='motivo_consulta',
            field=models.TextField(verbose_name='Motivo de Consulta'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='observaciones_privadas',
            field=models.TextField(blank=True, help_text='Notas privadas para el equipo de la clínica', null=True, verbose_name='Notas Internas'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='peso_actual_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='temperatura_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp (°C)'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='tratamiento',
            field=models.TextField(help_text='Indicaciones, medicamentos recetados y procedimientos', verbose_name='Tratamiento e Indicaciones'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta', to='turnos.turno', verbose_name='Turno Asociado'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='turnos.veterinario', verbose_name='Veterinario Atendiente'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='dosis',
            field=models.CharField(blank=True, help_text='Ej: 1 comprimido, 0.5 ml', max_length=50, null=True, verbose_name='Dosis Suministrada'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='fecha_aplicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aplicación'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='fecha_proxima_dosis',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Dosis'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones', to='clientes.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='producto',
            field=models.CharField(help_text='Ej: Total Full, Simparica, Bravecto', max_length=100, verbose_name='Producto Utilizado'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='tipo',
            field=models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa (Pulgas/Garrapatas)'), ('AMBAS', 'Ambas')], default='INTERNA', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.veterinario', verbose_name='Veterinario Atendiente'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='fecha_aplicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aplicación'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='fecha_proxima_dosis',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Dosis / Revacunación'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de Lote'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='clientes.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='nombre_vacuna',
            field=models.CharField(help_text='Ej: Quíntuple, Antirrábica, Séxtuple', max_length=100, verbose_name='Nombre de Vacuna'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.veterinario', verbose_name='Veterinario Atendiente'),
        ),
    ]
