# Generated by Django 6.0.7 on 2026-08-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0003_consultamedica_actualizado_el_and_more'),
        ('usuarios', '0002_perfilusuario_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medicas', to='usuarios.veterinaria', verbose_name='Veterinaria'),
        ),
        migrations.AlterField(
            model_name='registrodesparasitacion',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones_aplicadas', to='usuarios.veterinaria', verbose_name='Veterinaria'),
        ),
        migrations.AlterField(
            model_name='registrovacuna',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='usuarios.veterinaria', verbose_name='Veterinaria'),
        ),
    ]
