# Generated by Django 6.0.7 on 2026-08-11 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_historiaclinica_mascota_and_more'),
        ('historia_clinica', '0004_alter_consultamedica_veterinaria_and_more'),
        ('turnos', '0002_alter_veterinario_options_turno_actualizado_and_more'),
        ('usuarios', '0003_veterinaria_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Ecografía Abdominal, Hemograma Completo', max_length=150, verbose_name='Título del Estudio')),
                ('tipo_estudio', models.CharField(choices=[('ECOGRAFIA', 'Ecografía'), ('RADIOGRAFIA', 'Radiografía (RX)'), ('ANALISIS_SANGRE', 'Análisis de Sangre / Laboratorio'), ('URANALISIS', 'Análisis de Orina'), ('CITOLOGIA', 'Citología / Histopatología'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma (ECG)'), ('OTRO', 'Otro Estudio / Adjunto')], default='OTRO', max_length=30, verbose_name='Categoría / Tipo')),
                ('archivo', models.FileField(upload_to='estudios/%Y/%m/', verbose_name='Archivo / Adjunto (PDF, JPG, PNG, DICOM)')),
                ('fecha_estudio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Estudio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Informe / Conclusiones del Estudio')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='historia_clinica.consultamedica', verbose_name='Consulta Asociada')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='clientes.mascota', verbose_name='Mascota')),
                ('veterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudios_medicos', to='usuarios.veterinaria', verbose_name='Veterinaria')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.veterinario', verbose_name='Veterinario Solicitante/Cargador')),
            ],
            options={
                'verbose_name': 'Estudio Médico',
                'verbose_name_plural': 'Estudios Médicos',
                'ordering': ['-fecha_estudio', '-creado_el'],
            },
        ),
    ]
