# Generated by Django 6.0.7 on 2026-09-09 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_historiaclinica_mascota_and_more'),
        ('historia_clinica', '0005_estudiomedico'),
        ('turnos', '0002_alter_veterinario_options_turno_actualizado_and_more'),
        ('usuarios', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jaula / Box')),
                ('motivo_ingreso', models.TextField(verbose_name='Motivo de Internación')),
                ('diagnostico_ingreso', models.TextField(blank=True, null=True, verbose_name='Diagnóstico al Ingreso')),
                ('dieta_indicaciones', models.TextField(blank=True, null=True, verbose_name='Dieta e Indicaciones Generales')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Ingreso')),
                ('fecha_alta_estimada', models.DateField(blank=True, null=True, verbose_name='Alta Estimada')),
                ('fecha_alta_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Alta')),
                ('estado', models.CharField(choices=[('INTERNADO', 'Internado / En Curso'), ('ALTA', 'Alta Médica'), ('FALLECIDO', 'Fallecimiento'), ('DERIVADO', 'Derivado / Trasladado')], default='INTERNADO', max_length=15, verbose_name='Estado')),
                ('resumen_alta', models.TextField(blank=True, null=True, verbose_name='Resumen / Epicrisis de Alta')),
                ('costo_dia_estadia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo por Día de Estadía')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('consulta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internacion_derivada', to='historia_clinica.consultamedica', verbose_name='Consulta que Origina el Ingreso')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaciones', to='clientes.mascota', verbose_name='Mascota')),
                ('veterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internaciones', to='usuarios.veterinaria', verbose_name='Veterinaria')),
                ('veterinario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internaciones_a_cargo', to='turnos.veterinario', verbose_name='Veterinario Responsable')),
            ],
            options={
                'verbose_name': 'Internación',
                'verbose_name_plural': 'Internaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('estado_general', models.CharField(choices=[('ESTABLE', 'Estable'), ('MEJORANDO', 'Mejorando'), ('SIN_CAMBIOS', 'Sin Cambios'), ('EMPEORANDO', 'Empeorando'), ('CRITICO', 'Crítico')], default='ESTABLE', max_length=15, verbose_name='Estado General del Paciente')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp (°C)')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='FC (LPM)')),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True, verbose_name='FR (RPM)')),
                ('notas', models.TextField(verbose_name='Evolución Clínica / Novedades')),
                ('medicacion_administrada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medicación / Procedimiento Administrado')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones_registradas', to='turnos.veterinario', verbose_name='Veterinario')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='historia_clinica.internacion', verbose_name='Internación')),
            ],
            options={
                'verbose_name': 'Evolución de Internación',
                'verbose_name_plural': 'Evoluciones de Internación',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
