# Generated by Django 6.0.7 on 2026-09-19 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_usuario'),
        ('historia_clinica', '0006_internacion_evolucioninternacion'),
        ('turnos', '0003_solicitudturnoweb'),
        ('usuarios', '0007_precio_real_plan_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('diagnostico', models.CharField(blank=True, max_length=255, verbose_name='Diagnóstico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='historia_clinica.consultamedica', verbose_name='Consulta Asociada')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='clientes.mascota', verbose_name='Mascota')),
                ('veterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='usuarios.veterinaria', verbose_name='Veterinaria')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='turnos.veterinario', verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dosis', models.CharField(blank=True, max_length=150, verbose_name='Dosis')),
                ('duracion', models.CharField(blank=True, max_length=150, verbose_name='Duración')),
                ('indicaciones', models.CharField(blank=True, max_length=255, verbose_name='Indicaciones')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='historia_clinica.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ítem de Receta',
                'verbose_name_plural': 'Ítems de Receta',
            },
        ),
    ]
