# Generated by Django 6.0.7 on 2026-09-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_usuario'),
        ('historia_clinica', '0007_receta_itemreceta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenClinicoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Resumen')),
                ('generado_el', models.DateTimeField(auto_now=True, verbose_name='Generado el')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_ia', to='clientes.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Resumen Clínico (IA)',
                'verbose_name_plural': 'Resúmenes Clínicos (IA)',
            },
        ),
    ]
