# Generated by Django 6.0.7 on 2026-08-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_mascota_options_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.veterinaria', verbose_name='Veterinaria')),
            ],
        ),
    ]
