# Generated by Django 6.0.7 on 2026-08-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_propietario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='veterinaria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.veterinaria', verbose_name='Veterinaria'),
        ),
        migrations.DeleteModel(
            name='ConsultaMedica',
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
