# Generated by Django 6.0.7 on 2026-08-02 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad / Ampolla / Frasco'), ('ML', 'Mililitros (ml)'), ('MG', 'Miligramos (mg)'), ('COMPRIMIDO', 'Comprimidos / Pastillas'), ('KG', 'Kilogramos (kg)')], default='UNIDAD', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, help_text='Alerta cuando el stock sea menor a este valor', max_digits=10)),
                ('requiere_receta', models.BooleanField(default=False)),
                ('es_vacuna', models.BooleanField(default=False, help_text='Marcar si se descuenta automáticamente al aplicar en Historia Clínica')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto / Insumo',
                'verbose_name_plural': 'Productos e Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada / Compra'), ('SALIDA_CONSULTA', 'Salida por Uso en Consulta'), ('SALIDA_VENTA', 'Salida por Venta Directa'), ('AJUSTE_PERDIDA', 'Ajuste / Merma / Vencimiento')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
