# Generated by Django 6.0.7 on 2026-08-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_remove_producto_activo_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='veterinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.veterinaria', verbose_name='Veterinaria'),
            preserve_default=False,
        ),
    ]
