# Generated by Django 6.0.7 on 2026-08-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_veterinaria'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('veterinaria', 'codigo_barras')},
        ),
    ]
