# Generated by Django 6.0.7 on 2026-08-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_codigo_barras_and_more'),
        ('usuarios', '0002_perfilusuario_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoria',
            name='veterinaria',
            field=models.ForeignKey(blank=True, help_text='Si se deja en blanco, la categoría será global para todas las veterinarias.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_inventario', to='usuarios.veterinaria', verbose_name='Veterinaria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento / Fármaco'), ('VACUNA', 'Vacuna'), ('ALIMENTO', 'Alimento / Nutrición'), ('DESCARTABLE', 'Material Descartable'), ('OTRO', 'Otro insumo')], default='MEDICAMENTO', max_length=20, verbose_name='Tipo de Insumo'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('veterinaria', 'nombre')},
        ),
    ]
