# Generated by Django 6.0.7 on 2026-10-01 19:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_unique_together_categoria_veterinaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El precio de venta tiene que ser mayor a $0.')], verbose_name='Precio de Venta'),
        ),
    ]
