# Generated by Django 6.0.7 on 2026-10-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento / Fármaco'), ('VACUNA', 'Vacuna'), ('ALIMENTO', 'Alimento / Nutrición'), ('DESCARTABLE', 'Material Descartable'), ('OTRO', 'Otro insumo'), ('SERVICIO', 'Servicio (consulta, cirugía, baño, etc.)')], default='MEDICAMENTO', max_length=20, verbose_name='Tipo de Insumo'),
        ),
    ]
