# Generated by Django 6.0.7 on 2026-08-09 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_historiaclinica_mascota_and_more'),
        ('turnos', '0001_initial'),
        ('usuarios', '0002_perfilusuario_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veterinario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Veterinario', 'verbose_name_plural': 'Veterinarios'},
        ),
        migrations.AddField(
            model_name='turno',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='turno',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='veterinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.veterinaria', verbose_name='Veterinaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterinario_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinarios', to='usuarios.veterinaria', verbose_name='Veterinaria'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Consulta'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='turnos.veterinario', verbose_name='Veterinario Asignado'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='Matrícula Profesional'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterUniqueTogether(
            name='veterinario',
            unique_together={('veterinaria', 'matricula')},
        ),
    ]
