# Generated by Django 6.0.7 on 2026-09-10 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_veterinario_options_turno_actualizado_and_more'),
        ('usuarios', '0005_plan_registroauditoria_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTurnoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.CharField(max_length=150, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('nombre_mascota', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('especie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especie')),
                ('motivo', models.TextField(verbose_name='Motivo de la Consulta')),
                ('fecha_deseada', models.DateField(verbose_name='Fecha Deseada')),
                ('franja_preferida', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('CUALQUIERA', 'Cualquier horario')], default='CUALQUIERA', max_length=15, verbose_name='Horario Preferido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('CONTACTADO', 'Contactado / En Gestión'), ('DESCARTADO', 'Descartado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('turno_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='turnos.turno', verbose_name='Turno Agendado')),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_turno_web', to='usuarios.veterinaria', verbose_name='Veterinaria')),
            ],
            options={
                'verbose_name': 'Solicitud de Turno Web',
                'verbose_name_plural': 'Solicitudes de Turno Web',
                'ordering': ['-creado_el'],
            },
        ),
    ]
