# Generated by Django 6.0.7 on 2026-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_solicitudturnoweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='recordatorio_whatsapp_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio de WhatsApp enviado'),
        ),
    ]
