# Generated by Django 6.0.7 on 2026-08-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Requiere aprobación de un superusuario antes de poder iniciar sesión.', verbose_name='Aprobado por Admin'),
        ),
    ]
