# Generated by Django 6.0.7 on 2026-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_veterinarias/', verbose_name='Logo Institucional'),
        ),
    ]
