# Generated by Django 6.0.7 on 2026-09-10 00:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_mensajecontacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Plan')),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mensual')),
                ('max_usuarios', models.PositiveIntegerField(default=3, verbose_name='Máximo de Usuarios')),
                ('max_mascotas', models.PositiveIntegerField(default=100, verbose_name='Máximo de Pacientes Activos')),
                ('permite_internacion', models.BooleanField(default=True, verbose_name='¿Incluye módulo de Internación?')),
                ('permite_multiples_veterinarios', models.BooleanField(default=True, verbose_name='¿Permite múltiples veterinarios?')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Beneficios')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Plan disponible para contratar?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden', 'precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGIN_FALLIDO', 'Intento de Login Fallido'), ('LOGOUT', 'Cierre de Sesión'), ('APROBACION', 'Aprobación de Acceso')], max_length=15, verbose_name='Acción')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad Afectada')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del Registro')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('veterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='usuarios.veterinaria', verbose_name='Veterinaria')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('PRUEBA', 'Período de Prueba')], default='PRUEBA', max_length=10, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Próximo Vencimiento / Renovación')),
                ('ultimo_pago_registrado', models.DateField(blank=True, null=True, verbose_name='Fecha del Último Pago Registrado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Internas de Facturación')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='usuarios.plan', verbose_name='Plan Contratado')),
                ('veterinaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='usuarios.veterinaria', verbose_name='Veterinaria')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
