# Generated by Django 6.0.7 on 2026-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_plan_registroauditoria_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio_anual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Anual'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='ciclo_facturacion',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10, verbose_name='Ciclo de Facturación'),
        ),
    ]
