# Generated by Django 6.0.7 on 2026-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_precio_real_plan_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='mp_access_token',
            field=models.CharField(blank=True, help_text='Access Token de PRODUCCIÓN de la cuenta de Mercado Pago de esta clínica (no la del superadmin), para cobrar ventas por QR. Se obtiene en mercadopago.com.ar/developers/panel. El dinero cobrado va directo a esta cuenta, VeterSystem no lo toca.', max_length=255, null=True, verbose_name='Access Token de Mercado Pago'),
        ),
    ]
