# Generated by Django 6.0.7 on 2026-10-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_veterinaria_mp_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='mp_pos_external_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID de punto de venta en Mercado Pago'),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='mp_store_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de tienda en Mercado Pago'),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de usuario en Mercado Pago'),
        ),
    ]
