# Generated by Django 6.0.7 on 2026-08-12 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_veterinaria_logo'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Inicial (Mano de Caja)')),
                ('monto_final_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Final Real en Arqueo')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_apertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('veterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_diarias', to='usuarios.veterinaria')),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Cajas Diarias',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cajadiaria'),
        ),
    ]
