# Generated by Django 6.0.7 on 2026-10-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_usuario'),
        ('inventario', '0005_alter_producto_unique_together_categoria_veterinaria_and_more'),
        ('usuarios', '0008_veterinaria_mp_access_token'),
        ('ventas', '0003_gastocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR_MP', 'QR / Mercado Pago'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('MERCADO_PAGO', 'Mercado Pago / Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='CobroQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=12)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_qr', to='ventas.cajadiaria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobro_qr', to='ventas.venta')),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_qr', to='usuarios.veterinaria')),
            ],
            options={
                'verbose_name': 'Cobro por QR',
                'verbose_name_plural': 'Cobros por QR',
                'ordering': ['-creado_el'],
            },
        ),
    ]
