# Generated by Django 6.0.7 on 2026-10-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_producto_tipo'),
        ('ventas', '0005_cobroqr_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descripcion_personalizada',
            field=models.CharField(blank=True, help_text='Para cobrar algo puntual (ej. una internación con costo variable) sin tener que crear un Producto/Servicio en el catálogo.', max_length=255, verbose_name='Descripción (cargo sin producto de catálogo)'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
