# Generated by Django 6.0.7 on 2026-10-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_detalleventa_descripcion_personalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobroqr',
            name='mp_order_id',
            field=models.CharField(blank=True, help_text='Solo para cobros con QR real en el local (API de Orders), distinto del link de pago.', max_length=100, null=True, verbose_name='ID de orden de Mercado Pago'),
        ),
        migrations.AddField(
            model_name='cobroqr',
            name='mp_qr_data',
            field=models.TextField(blank=True, help_text='String que se convierte en imagen de QR para que el cliente escanee.', null=True, verbose_name='Datos del QR'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR_MP', 'Link de pago (Mercado Pago)'), ('QR_LOCAL', 'QR en el local (Mercado Pago)'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('MERCADO_PAGO', 'Mercado Pago / Transferencia')], default='EFECTIVO', max_length=20),
        ),
    ]
